version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing "
    pre_build:
        commands: 
            - echo "The pre build phase"
    build:
        commands:
            - echo "In the build block"
            - echo "Let us run some test"
            - grep -Fq "Congratulations" index.html
    post_build:
        commands:
            - echo "The post build phase"
            
